/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MessageDialogue.java
 *
 * Created on 2011-2-8, 17:12:13
 */

package cn.edu.xaut.VectorEncode;

/**
 * @author greensubmarine
 */

import cn.edu.xaut.SLGridDataNode.Util.*;
import org.jdom.Element;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class MessageDialogue extends javax.swing.JFrame {
MediateXML mediate = new MediateXML();
EncodeExample encode = new EncodeExample();
Map<String, String> vectornamemap = new HashMap<String, String>();
Map<int[], String> vectormaps = new HashMap<int[], String>();
ArrayList<int[]> nowprevectorelement = new ArrayList<int[]>();
ArrayList<int[]> nowpostvectorelement = new ArrayList<int[]>();
ArrayList<int[]> parentprevectorelement = new ArrayList<int[]>();
ArrayList<int[]> parentpostvectorelement = new ArrayList<int[]>();

/** Creates new form MessageDialogue */
public MessageDialogue() {
    initComponents();
    Element root = encode.Getroot(XMLFileBean.Getnewxmlfile());
    //Element originalroot = encode.Getroot(XMLFileBean.GetOriginalXMLFileName());
    // String newvectorxmlfile = mediate.GenerateVectorXMLFile(XMLFileBean.Getnewxmlfile());
    System.out.println(XMLFileBean.GetXMLFile());
    Element vectorroots = encode.Getroot(XMLFileBean.GetXMLFile());
    vectornamemap = encode.GetVectorElementNames(vectorroots);
    vectormaps = encode.GetVectorElements(vectorroots);
    String Elementname = encode.GetElementName(root);
    System.out.println(Elementname);
    ArrayList<int[]> nowprevectorelements = NowVectorPreElementBean.Getnowvectorpreelement();
    ArrayList<int[]> nowpostvectorelements = NowVectorPostElementBean.Getnowvectorpostelement();
    ArrayList<int[]> parentvectorpreelements = ParentVectorPreElementBean.Getparentprevectorelement();
    ArrayList<int[]> parentpostvectorelements = ParentVectorPostElementBean.Getparentvectorpostelement();
    vectornamemap.put("(10000,10000)", "Document");
    for (int i = 0; i < nowprevectorelements.size(); i++) {
        String vectorvalues = "(" + nowprevectorelements.get(i)[0] + "," + nowprevectorelements.get(i)[1] + ")";
        String parentvectorvalues = "(" + parentvectorpreelements.get(i)[0] + "," + parentvectorpreelements.get(i)[1] + ")";
        System.out.println(
                "当前节点的前序向量编码：(" + nowprevectorelements.get(i)[0] + "," + nowprevectorelements.get(i)[1] + ") "
                        + "当前元素名称：" + vectornamemap.get(vectorvalues)
                        + " 当前节点后序向量编码：(" + nowpostvectorelements.get(i)[0] + "," + nowpostvectorelements.get(i)[1] + ") "
                        + " 父节点前序向量编码：(" + parentvectorpreelements.get(i)[0] + "," + parentvectorpreelements.get(i)[1] + ")"
                        + "父节点元素名称: " + vectornamemap.get(parentvectorvalues)
                        + " 父节点后序向量编码：(" + parentpostvectorelements.get(i)[0] + "," + parentpostvectorelements.get(i)[1] + ")");
    }
}

/** This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setName("Form"); // NOI18N

    jLabel1.setText(org.openide.util.NbBundle.getMessage(MessageDialogue.class, "MessageDialogue.jLabel1.text")); // NOI18N
    jLabel1.setName("jLabel1"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                      .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addComponent(jLabel1)
                                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
}// </editor-fold>//GEN-END:initComponents

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {

            new MessageDialogue().setVisible(true);
        }
    });
}

// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JLabel jLabel1;
// End of variables declaration//GEN-END:variables

}
