/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package cn.edu.xaut.SLGridDataNode.GUI;

/**
 * @author Administrator
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddDataNodeJFrame.java
 *
 * Created on 2010-3-29, 10:31:47
 */

import cn.edu.xaut.SLGridDataNode.LoginNode;
import cn.edu.xaut.SLGridDataNode.Tool.ScreenSize;
import cn.edu.xaut.SLGridDataNode.Util.AddDataNode;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.input.SAXBuilder;
import org.jdom.output.XMLOutputter;

import javax.swing.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;

public class AddNode extends javax.swing.JFrame {
AddDataNode addnode = new AddDataNode();
FileInputStream fileinputstream = null;

/** Creates new form AddDataNodeJFrame */
public AddNode() {
    initComponents();
    setBounds((ScreenSize.getWidth() - getWidth()) / 2, (ScreenSize.getHeight() - getHeight()) / 2, getWidth(), getHeight());
}

/** This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jComboBox1 = new javax.swing.JComboBox();
    jTextField4 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    new cn.edu.xaut.SLGridDataNode.Util.PlafView().ChangeView();
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("华文行楷", 1, 24)); // NOI18N
    jLabel1.setText("添加数据节点");

    jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
    jLabel2.setText("节点IP:");

    jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
    jLabel3.setText("用户名称：");

    jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
    jLabel4.setText("用户密码：");

    jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
    jLabel5.setText("服务器类型：");

    jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
    jLabel6.setText("服务器端口：");

    jTextField1.setBackground(new java.awt.Color(255, 255, 255));

    jTextField2.setBackground(new java.awt.Color(255, 255, 255));

    jTextField3.setBackground(new java.awt.Color(255, 255, 255));

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"SQLServer2000", "SQLServer2005", "MYSQL", "DB2"}));

    jTextField4.setBackground(new java.awt.Color(255, 255, 255));

    jButton1.setText("添加");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("重置");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                          .addGap(58, 58, 58)
                                                                          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                            .addComponent(jLabel5)
                                                                                            .addComponent(jLabel6)
                                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addComponent(jLabel3))
                                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                              .addComponent(jLabel4)
                                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                                                                                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                                                                                                .addComponent(jComboBox1, 0, 180, Short.MAX_VALUE)))
                                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                              .addGap(27, 27, 27)
                                                                                                              .addComponent(jButton1)
                                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                                                                                              .addComponent(jButton2)
                                                                                                              .addGap(18, 18, 18))))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                          .addGap(106, 106, 106)
                                                                          .addComponent(jLabel1)))
                                      .addContainerGap(61, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addComponent(jLabel1)
                                      .addGap(28, 28, 28)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGap(18, 18, 18)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGap(27, 27, 27)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGap(29, 29, 29)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGap(18, 18, 18)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGap(18, 18, 18)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton2))
                                      .addContainerGap(27, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addContainerGap())
    );

    pack();
    this.setResizable(false);
    this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
}// </editor-fold>

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    String poolname = jTextField1.getText().trim();
    String username = jTextField2.getText().trim();
    String password = jTextField3.getText().trim();
    String port = jTextField4.getText().trim();
    String dbtype = (String) jComboBox1.getSelectedItem();
    String url = null;
    String Standardjdbcurl = null;
    if (poolname.length() == 0 || username.length() == 0 || password.length() == 0 || port.length() == 0 || dbtype.length() == 0) {
        JOptionPane.showMessageDialog(null, "请输入正确的信息");
        return;
    } else {
        addnode.setPoolname(poolname);
        addnode.setUsername(username);
        addnode.setPassword(password);
        addnode.setPort(port);
        if (dbtype.equals("SQLServer2005")) {
            addnode.setDriver("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            url = "jdbc:sqlserver://" + addnode.getPoolname() + ":" + addnode.getPort() + ";DatabaseName=master";
            Standardjdbcurl = "jdbc:sqlserver://" + addnode.getPoolname() + ":" + addnode.getPort() + ";DatabaseName=XR_System";
        }
        if (dbtype.equals("MYSQL")) {
            addnode.setDriver("com.mysql.jdbc.Driver");
            url = "jdbc:mysql://" + addnode.getPoolname() + ":" + addnode.getPort() + "/mysql";
            Standardjdbcurl = "jdbc:mysql://" + addnode.getPoolname() + ":" + addnode.getPort() + "/XR_System";
        }
        if (dbtype.equals("SQLServer2000")) {
            addnode.setDriver("com.microsoft.jdbc.sqlserver.SQLServerDriver");
            url = "jdbc:microsoft:sqlserver://" + addnode.getPoolname() + ":" + addnode.getPort() + ";DatabaseName=master";
            Standardjdbcurl = "jdbc:microsoft:sqlserver://" + addnode.getPoolname() + ":" + addnode.getPort() + ";DatabaseName=XR_System";
        }
    }
    try {
        fileinputstream = new FileInputStream("config.xml");
        SAXBuilder builder = new SAXBuilder();
        Document doc = builder.build(fileinputstream);
        Element root = doc.getRootElement();
        Element pool = new Element("pool");
        Element name = new Element("name");
        Element nodeusername = new Element("username");
        Element nodepassword = new Element("password");
        Element standardjdbcurl = new Element("Standardjdbcurl");
        Element jdbcurl = new Element("jdbcurl");
        Element driver = new Element("driver");
        Element wait = new Element("wait");
        Element maxconn = new Element("maxconn");
        pool.addContent(name);
        pool.addContent(nodeusername);
        pool.addContent(nodepassword);
        pool.addContent(standardjdbcurl);
        pool.addContent(jdbcurl);
        pool.addContent(driver);
        pool.addContent(wait);
        pool.addContent(maxconn);
        root.addContent(pool);
        name.setText(addnode.getPoolname().toString());
        nodeusername.setText(addnode.getUsername().toString());
        nodepassword.setText(addnode.getPassword().toString());
        standardjdbcurl.setText(Standardjdbcurl.toString());
        jdbcurl.setText(url.toString());
        driver.setText(addnode.getDriver().toString());
        wait.setText("0");
        maxconn.setText("1000");
        XMLOutputter output = new XMLOutputter();
        output.output(doc, new FileOutputStream("config.xml"));
        System.out.println("添加元素成功！！！");
        JOptionPane.showMessageDialog(null, "添加元素成功！！！");
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        new AddNode().setVisible(true);
    } catch (Exception e) {
        e.printStackTrace();
        System.out.println("添加元素失败！！！");
        JOptionPane.showMessageDialog(null, "添加元素失败！！！");
    }
}

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "您确定已经返回!!!");
    this.setVisible(false);
    new LoginNode().setVisible(true);
}

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {
            try {
                UIManager.setLookAndFeel(new com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel());
                new AddNode().setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    });
}

// Variables declaration - do not modify
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JComboBox jComboBox1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JPanel jPanel1;
private javax.swing.JTextField jTextField1;
private javax.swing.JTextField jTextField2;
private javax.swing.JTextField jTextField3;
private javax.swing.JTextField jTextField4;
// End of variables declaration

}

