/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package cn.edu.xaut.SLGridDataNode.GUI;

/**
 * @author Administrator
 */

import cn.edu.xaut.SLGridDataNode.Tool.ScreenSize;
import cn.edu.xaut.SLGridDataNode.dao.DBConnection;

import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

public class DelData extends JFrame {
/** Creates new form DelData */
public DelData() {
    initComponents();
    setBounds((ScreenSize.getWidth() - getWidth()) / 2, (ScreenSize.getHeight() - getHeight()) / 2, getWidth(), getHeight());
}

/** This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    ArrayList<String> DocList = new ArrayList<String>();
    new cn.edu.xaut.SLGridDataNode.Util.PlafView().ChangeView();
    boolean flag = true;

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setName("jPanel1"); // NOI18N

    jLabel1.setText("请选择要删除的数据：");
    jLabel1.setName("jLabel1"); // NOI18N

    //jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.setName("jComboBox1"); // NOI18N
    DocList = this.GetDocList();
    for (int m = 0; m < DocList.size(); m++)
        jComboBox1.addItem(DocList.get(m).toString());

    jButton1.setText("全部删除");
    jButton1.setName("jButton1"); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("删除数据");
    jButton2.setName("jButton2"); // NOI18N
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            //jButton2ActionPerformed(evt);
            ArrayList<String> NowList = new ArrayList<String>();
            String NowDoc = (String) jComboBox1.getSelectedItem();
            String DelDoc =
                    "DELETE FROM  namespace WHERE documentid = (SELECT documentid FROM document WHERE documentname='" + NowDoc + "'); " +
                            "DELETE FROM  text WHERE documentid = (SELECT documentid FROM document WHERE documentname='" + NowDoc + "'); " +
                            "DELETE FROM  attribute WHERE documentid = (SELECT documentid FROM document WHERE documentname='" + NowDoc + "'); " +
                            "DELETE FROM  element WHERE documentid = (SELECT documentid FROM document WHERE documentname='" + NowDoc + "'); " +
                            "DELETE FROM  document WHERE documentname='" + NowDoc + "'; ";
            //String DropView = "DROP VIEW "+"["+NowDoc+"]";
            try {
                new DBConnection().ExecuteInsert(DelDoc);
            } catch (Exception e) {
                e.printStackTrace();
            }
                /*try {
                    new DBConnection().ExecuteInsert(DropView);
                } catch(Exception e){e.printStackTrace();}*/
            NowList = GetDocList();
            for (int m = 0; m < NowList.size(); m++)
                jComboBox1.addItem(NowList.get(m).toString());
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                  .addContainerGap(45, Short.MAX_VALUE)
                                                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                                                                                                  .addComponent(jButton1)
                                                                                                                                                                  .addGap(32, 32, 32))
                                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                                                                                                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                  .addGap(18, 18, 18)))
                                                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(jButton2)
                                                                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                  .addGap(39, 39, 39))
    );
    jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                                      .addGap(20, 20, 20)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1))
                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton2)
                                                        .addComponent(jButton1))
                                      .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
}// </editor-fold>

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    ArrayList<String> NowList = new ArrayList<String>();
    NowList = this.GetDocList();
    String DelDoc =
            "DELETE FROM namespace ;" +
                    "DELETE FROM text ;" +
                    "DELETE FROM element ;" +
                    "DELETE FROM attribute ;" +
                    "DELETE FROM document ;";

    //String DropView = "DROP VIEW ";
    try {
        new DBConnection().ExecuteInsert(DelDoc);
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private ArrayList<String> GetDocList() {
    String SQLString = "SELECT documentname FROM document";
    ArrayList<String> DocList = new ArrayList<String>();
    ResultSet rs = null;
    //rs = new DBConnection().ExecuteSQL(SQLString);
    try {
        rs = new DBConnection().ExecuteSQL(SQLString);
        while (rs.next()) {
            DocList.add(rs.getString(1));
        }
    } catch (SQLException e) {
        e.printStackTrace();
    } catch (Exception e) {
        e.printStackTrace();
    }
    return DocList;
}

// Variables declaration - do not modify
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JComboBox jComboBox1;
private javax.swing.JLabel jLabel1;
private javax.swing.JPanel jPanel1;
// End of variables declaration
}
