package cn.edu.xaut.SLGridDataNode.GUI;

/**
 * @author greensubmarine
 */

import cn.edu.xaut.SLGridDataNode.Access.ImageToXml;
import cn.edu.xaut.SLGridDataNode.Tool.ScreenSize;
import cn.edu.xaut.SLGridDataNode.dao.DBConnection;
import cn.edu.xaut.SLGridDataNode.dao.ResultSetTableModel;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.sql.ResultSet;


public class MainFrame extends javax.swing.JFrame {

/** Creates new form MainFrame */
public MainFrame() {
    initComponents();
    setBounds((ScreenSize.getWidth() - getWidth()) / 2, (ScreenSize.getHeight() - getHeight()) / 2, getWidth(), getHeight());
}

/** This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
// <editor-fold defaultstate="collapsed" desc=" 系统主界面 ">
private void initComponents() {
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();

    //jTable1 = new javax.swing.JTable();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JSeparator();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenuItem5 = new javax.swing.JMenuItem();
    jSeparator2 = new javax.swing.JSeparator();
    jMenuItem6 = new javax.swing.JMenuItem();
    jMenu3 = new javax.swing.JMenu();
    jMenuItem8 = new javax.swing.JMenuItem();
    jSeparator3 = new javax.swing.JSeparator();
    jMenuItem9 = new javax.swing.JMenuItem();
    jMenuItem10 = new javax.swing.JMenuItem();
    jMenu4 = new javax.swing.JMenu();
    jMenuItem7 = new javax.swing.JMenuItem();
    jMenu5 = new javax.swing.JMenu();
    jMenuItem11 = new javax.swing.JMenuItem();
    jMenuItem12 = new javax.swing.JMenuItem();

    new cn.edu.xaut.SLGridDataNode.Util.PlafView().ChangeView();
    setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    setTitle("平台主界面");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setLocationByPlatform(true);
    jScrollPane1.setToolTipText("\u5df2\u5b58\u50a8\u7684XML\u6587\u6863");
    jScrollPane1.setEnabled(false);
    jScrollPane1.setFont(new java.awt.Font("宋体", 1, 12));
    String SQLString = "USE xr_system SELECT DocumentID AS 元数据编号, DocumentName AS 元数据名称, StoredTime AS 存储时间 FROM Document";
    rs = new DBConnection().ExecuteSQL(SQLString);
    if (rs != null) {
        model = new ResultSetTableModel(rs);
        jTable1 = new javax.swing.JTable(model);
        jTable1.setFont(new java.awt.Font("宋体", 1, 16));
    } else {
        Object[][] cells =
                {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                };
        String[] ColNames = {"文档编号", "文档名", "存储时间"};
        jTable1 = new javax.swing.JTable(cells, ColNames);
    }

    jScrollPane1.setViewportView(jTable1);

    org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                                 .addContainerGap()
                                 .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                                 .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                                 .addContainerGap()
                                 .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                                 .addContainerGap())
    );

    jMenu1.setText("\u6587\u4ef6");
    jMenu1.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenu1ActionPerformed(evt);
        }
    });

    jMenuItem1.setText("元数据存储");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem1ActionPerformed(evt);
        }
    });

    jMenu1.add(jMenuItem1);

    jMenu1.add(jSeparator1);

    jMenuItem2.setText("\u9000\u51fa");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });

    jMenu1.add(jMenuItem2);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("\u5173\u7cfb\u6570\u636e");
    jMenuItem3.setText("\u8868[Element]");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });

    jMenu2.add(jMenuItem3);

    jMenuItem4.setText("\u8868[Attribute]");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
        }
    });

    jMenu2.add(jMenuItem4);

    jMenuItem5.setText("\u8868[Text]");
    jMenuItem5.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem5ActionPerformed(evt);
        }
    });

    jMenu2.add(jMenuItem5);

    //jMenu2.add(jSeparator2);

    jMenuItem6.setText("\u89c6\u56fe");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem6ActionPerformed(evt);
        }
    });

    jMenu2.add(jMenuItem6);

    jMenu2.add(jSeparator2);

    jMenuItem10.setText("\u5220\u9664\u6570\u636e");
    jMenuItem10.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem10ActionPerformed(evt);
        }
    });

    jMenu2.add(jMenuItem10);
    jMenuBar1.add(jMenu2);

    jMenu3.setText("元数据管理");
    jMenuItem8.setText("导出元数据");
    jMenuItem8.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem8ActionPerformed(evt);
        }
    });

    jMenu3.add(jMenuItem8);
    jMenu3.add(jSeparator3);

    jMenuItem9.setText("查询元数据");
    jMenuItem9.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem9ActionPerformed(evt);
        }
    });

    jMenu3.add(jMenuItem9);

    jMenuItem12.setText("图像类元数据查看");
    jMenuItem12.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(ActionEvent e) {
            jMenuItem12ActionPerformed(e);
        }
    });

    jMenu3.add(jMenuItem12);

    jMenuBar1.add(jMenu3);

    jMenu4.setText("\u5e2e\u52a9");
    jMenuItem7.setText("\u5173\u4e8e...");
    jMenuItem7.setToolTipText("\u5df2\u5b58\u50a8\u7684XML\u6587\u6863");
    jMenuItem7.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem7ActionPerformed(evt);
        }
    });

    jMenu4.add(jMenuItem7);

    jMenuBar1.add(jMenu4);

    jMenuBar1.add(jMenu5);

    jMenu5.setText("节点信息查看");

    jMenu5.add(jMenuItem11);

    jMenuItem11.setText("节点登录");

    jMenuItem11.addActionListener(new java.awt.event.ActionListener() {


        public void actionPerformed(ActionEvent evt) {
            jMenu5ActionPerformed(evt);
        }
    });

    setJMenuBar(jMenuBar1);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                                 .addContainerGap()
                                 .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                                 .addContainerGap()
                                 .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addContainerGap())
    );
    pack();
}// </editor-fold>

private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    new QueryXMLDoc().setVisible(true);
}

private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    new ExportXMLDoc().setVisible(true);
}

private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    new About().setVisible(true);
}

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    new XMLView().setVisible(true);
}

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    new TextTable().setVisible(true);
}

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    new AttributeTable().setVisible(true);
}

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    new ElementTable().setVisible(true);
}

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    //setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    new StoreXMLFrame().setVisible(true);
}

private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    //
    //System.out.println("dfgdbbg");
}

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
    setVisible(false);
    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    // new cn.edu.xaut.SLMetaDataBase.LoginDataNode().setVisible(true);// TODO 将在此处添加您的处理代码：
}

private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO 将在此处添加您的处理代码：
    new DelData().setVisible(true);
}

private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {

}

private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent e) {
    openImageFile();
}

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {
            new MainFrame().setVisible(true);
            //InitTable();
        }
    });
}

private void InitTable() {
}

// 变量声明 - 不进行修改
private javax.swing.JMenu jMenu1;
private javax.swing.JMenu jMenu2;
private javax.swing.JMenu jMenu3;
private javax.swing.JMenu jMenu4;
private javax.swing.JMenu jMenu5;
private javax.swing.JMenuBar jMenuBar1;
private javax.swing.JMenuItem jMenuItem1;
private javax.swing.JMenuItem jMenuItem2;
private javax.swing.JMenuItem jMenuItem3;
private javax.swing.JMenuItem jMenuItem4;
private javax.swing.JMenuItem jMenuItem5;
private javax.swing.JMenuItem jMenuItem6;
private javax.swing.JMenuItem jMenuItem7;
private javax.swing.JMenuItem jMenuItem8;
private javax.swing.JMenuItem jMenuItem9;
private javax.swing.JMenuItem jMenuItem10;
private javax.swing.JMenuItem jMenuItem11;
private javax.swing.JMenuItem jMenuItem12;
private javax.swing.JPanel jPanel1;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JSeparator jSeparator1;
private javax.swing.JSeparator jSeparator2;
private javax.swing.JSeparator jSeparator3;
private javax.swing.JTable jTable1;
private ResultSetTableModel model;
private ResultSet rs;
private String FilePath;

// 变量声明结束

private void openImageFile() {

    JFileChooser jFileChooser1 = new JFileChooser();
    jFileChooser1.setDialogTitle("打开图片类元数据");
    jFileChooser1.setCurrentDirectory(new File("."));
    jFileChooser1.setFileFilter(new javax.swing.filechooser.FileFilter() {


        public boolean accept(File f) {
            return f.isDirectory() || f.getName().toLowerCase().endsWith(".xml");
        }


        public String getDescription() {
            return "image XML files";
        }
    });

    int r = jFileChooser1.showOpenDialog(this);
    if (r != JFileChooser.APPROVE_OPTION) return;
    File f = jFileChooser1.getSelectedFile();
    FilePath = f.getAbsolutePath();
    System.out.println(FilePath);
    ImageToXml ixl = new ImageToXml(FilePath.toString());
    ixl.xmlToImage("D:\\5.jpg");
    JOptionPane.showMessageDialog(null, "Success");
}


}
