/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package cn.edu.xaut.SLGridDataNode.GUI;

/**
 * @author greensubmarine
 */

import cn.edu.xaut.SLGridDataNode.DBConnectionPool.AddPoolBean;
import cn.edu.xaut.SLGridDataNode.Tool.ScreenSize;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.input.SAXBuilder;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;

import javax.swing.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class registerframe1 extends javax.swing.JFrame {
AddPoolBean bean = new AddPoolBean();

/** Creates new form registerframe */
public registerframe1() {
    initComponents();
    setBounds((ScreenSize.getWidth() - getWidth()) / 2, (ScreenSize.getHeight() - getHeight()) / 2, getWidth(), getHeight());
}

/** This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    DBDriver = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jPasswordField1 = new javax.swing.JPasswordField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    new cn.edu.xaut.SLGridDataNode.Util.PlafView().ChangeView();
    setTitle("添加节点信息到数据库连接池中");
    setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    this.setVisible(true);
    jLabel1.setText("节点IP：");

    jLabel2.setText("端口号：");

    jLabel3.setText("数据库类型：");

    jLabel4.setText("用户名称：");

    jLabel5.setText("用户密码：");

    jTextField1.setBackground(new java.awt.Color(255, 255, 255));

    jTextField2.setBackground(new java.awt.Color(255, 255, 255));

    //DBDriver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SQLServer2000", "SQLServer2005", "DB2", "MYSQL", "ORACLE" }));


    jTextField3.setBackground(new java.awt.Color(255, 255, 255));

    jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));


    jButton1.setText("添加");
    jButton1.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("重置");
    jButton2.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                                      .addGap(47, 47, 47)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                          .addComponent(jButton1)
                                                                          .addGap(18, 18, 18)
                                                                          .addComponent(jButton2))
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                                        .addComponent(DBDriver, 0, 197, Short.MAX_VALUE)
                                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                      .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGap(28, 28, 28)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2))
                                      .addGap(28, 28, 28)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(DBDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGap(31, 31, 31)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGap(18, 18, 18)
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                                                          .addComponent(jButton1)
                                                                          .addContainerGap())
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                          .addComponent(jButton2)
                                                                          .addContainerGap())))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                  .addContainerGap()
                                                                                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                  .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addContainerGap())
    );

    pack();
}// </editor-fold>

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    IP = jTextField1.getText().trim();
    PortNum = jTextField2.getText().trim();
    Username = jTextField3.getText().trim();
    Password = jPasswordField1.getText().trim();
    DbType = DBDriver.getText().trim();
    addNodePools();
    JOptionPane.showMessageDialog(null, "已添加到连接池中");
    setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    //setVisible(false);
    // new loginexample1().setVisible(true);
}

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    new registerframe1();
}

// Variables declaration - do not modify
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JTextField DBDriver;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JPanel jPanel1;
private javax.swing.JPasswordField jPasswordField1;
private javax.swing.JTextField jTextField1;
private javax.swing.JTextField jTextField2;
private javax.swing.JTextField jTextField3;
// End of variables declaration
private static String IP, PortNum, Username, Password, DbType;
List db = new ArrayList();

public void addNodePools() {
    FileInputStream nodefileinputstream = null;
    FileOutputStream nodefileoutputstream = null;

    try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection conn = DriverManager.getConnection("jdbc:sqlserver://" + IP + ":" + PortNum + ";DatabaseName=master", Username, Password);
        Statement stat = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        ResultSet rs = stat.executeQuery("select [name] from master.dbo.sysdatabases where DBId>4 Order By [Name]");
        while (rs.next()) {
            db.add(rs.getString("name"));
        }

        nodefileinputstream = new FileInputStream("config.xml");
        SAXBuilder builder = new SAXBuilder();
        Document doc = builder.build(nodefileinputstream);
        Element root = doc.getRootElement();
        List nodepools = root.getChildren();
        for (int i = 0; i < db.size(); i++) {
            Element pool = new Element("pool");
            Element name = new Element("name");
            name.setText(db.get(i).toString());
            pool.addContent(name);
            Element username = new Element("username");
            username.setText(Username);
            pool.addContent(username);
            Element password = new Element("password");
            password.setText(Password);
            pool.addContent(password);
            Element driver = new Element("driver");
            driver.setText("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            pool.addContent(driver);

            Element jdbcurl = new Element("jdbcurl");
            jdbcurl.setText("jdbc:sqlserver://" + IP + ":" + PortNum + ";DatabaseName=" + db.get(i).toString() + "");
            pool.addContent(jdbcurl);

            Element wait = new Element("wait");
            wait.setText("0");
            pool.addContent(wait);
            Element maxconn = new Element("maxconn");
            maxconn.setText("1000");
            pool.addContent(maxconn);
            nodepools.add(pool);

        }

        Format format = Format.getPrettyFormat();
        format.setIndent("");
        format.setEncoding("UTF-8");
        XMLOutputter outp = new XMLOutputter(format);
        nodefileoutputstream = new FileOutputStream("config.xml");
        outp.output(doc, nodefileoutputstream);
        System.out.println("添加成功");
    } catch (Exception e) {
        e.printStackTrace();
    }
}
}
